POWERBI_EMBED_URL = "https://app.powerbi.com/reportEmbed?reportId=1e2d59bc-eabb-44c5-9ae8-30cc5cb73b7b&autoAuth=true&embeddedDemo=true"
REDDIT_CLIENT_ID="ac8sliEZ-jAhQ0QqnuZu0w"
REDDIT_SECRET="wX2CV_1-YFvAh2djLBzQZ4VVxx_XAA"
REDDIT_USER_AGENT="nutrition_dashboard_app by u/Connect-Caregiver-28"
YOUTUBE_API_KEY="AIzaSyBIMh2esXh6AvLqhdsGyhmGZnhq78lux2I"
TWITTER_BEARER_TOKEN="AAAAAAAAAAAAAAAAAAAAACwt2gEAAAAA%2FD6IgskkwC4ZwIxDdwxDrbd2I3U%3Db0Zf5cJeERDvtIf7uv6iOF2Qv2eF0Dn3zzRda5vE7uTvND58s9"